version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - '5775:5775/udp' # Legacy Thrift format over UDP
      - '6831:6831/udp' # Thrift Compact format over UDP
      - '6832:6832/udp' # Thrift Binary format over UDP
      - '5778:5778' # HTTP server for agent's health check and sampling strategies
      - '16686:16686' # Jaeger Query service web UI
      - '14250:14250' # Jaeger Collector for gRPC
      - '14268:14268' # Jaeger Collector for HTTP in Thrift format
      - '14269:14269' # Jaeger Collector admin endpoint
      - '9411:9411' # Zipkin-compatible endpoint
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP HTTP receiver
